services:
    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "rootpass"
            MYSQL_DATABASE: mydb
        ports:
            - "3307:3306"
